# Generated by Django 4.0.4 on 2022-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cositas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Precio', models.IntegerField()),
                ('Detalles', models.CharField(max_length=150)),
            ],
        ),
    ]
