# Generated by Django 4.0.4 on 2022-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cositas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos_imagenes'),
        ),
    ]
