# Generated by Django 4.0.4 on 2022-06-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cositas_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cositas',
            options={'verbose_name': 'cosas'},
        ),
    ]
