# Generated by Django 4.0.4 on 2022-06-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cositas_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cositas',
            old_name='imagen',
            new_name='Imagen',
        ),
    ]
