# Generated by Django 4.0.4 on 2022-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_imagen_cositas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField()),
                ('requisito', models.CharField(max_length=150)),
                ('objetos', models.CharField(max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='productos_imagenes')),
            ],
            options={
                'verbose_name': 'oferton',
            },
        ),
    ]
